project:
  title: "shiny-beginners"
  render:
    - "*.qmd"
    - "!LICENCE.md"
author: "ZoÃ« Turner"
format:
  revealjs:
    theme: [default, nhsr-quarto.scss]
    logo: https://raw.githubusercontent.com/nhs-r-community/assets/main/logo/nhsr-logo.svg
    code-link: true
    css: nhsr-quarto.scss
    preview-links: true
title-slide-attributes:
  data-background-color: "#43464B"
embed-resources: true
execute:
  echo: true
  eval: false